Jdp210101 15
piotr-grosicki/project-jdp-2101-01 pull request #14
Opened 2021-02-02 11:11 UTC by eimspl

2021-02-03 07:57 UTC, piotr-grosicki requested changes

2021-02-03 21:10 UTC, eimspl commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    /* @OneToMany(                       //potrzebuje encji order - chyba już jest...
ok, poszło jako nowy task

2021-02-04 08:20 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    /* @OneToMany(                       //potrzebuje encji order - chyba już jest...
nie powinno isc jako nowy task, powinno byc zmiana w tym PR. jezeli zmerguje ten task lub tamten to beda konflikty

2021-02-05 16:24 UTC, eimspl commented
Zmieniła się nam koncepcja relacji w bazie, przesyłam update.

2021-02-05 16:24 UTC, eimspl commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    /* @OneToMany(                       //potrzebuje encji order - chyba już jest...
ok, wszystko jasne :)

2021-02-05 17:28 UTC, piotr-grosicki approved these changes

2021-02-05 17:28 UTC, merged