Jdp210101 12
piotr-grosicki/project-jdp-2101-01 pull request #16
Opened 2021-02-03 00:38 UTC by Piotr1992

Encja Product - implementacja

2021-02-03 08:01 UTC, piotr-grosicki requested changes

2021-02-03 08:01 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    private Long groupId;
tutaj powinna znajdowac sie encja a nie id

2021-02-03 08:01 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +//    private ProductCards productCard;
pytanie na komunikatorze

2021-02-03 08:01 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +//    private QuantityProducts quantityProduct;
pytanie na komunikatorze

2021-02-05 18:12 UTC, piotr-grosicki requested changes

2021-02-05 18:12 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +//    private ProductCards productCard;
do poprawy zgodnie ze schematem bazy danych

2021-02-05 18:12 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +//    private QuantityProducts quantityProduct;
do poprawy zgodnie ze schematem bazy danych

2021-02-07 00:22 UTC, defiofi approved these changes

2021-02-08 01:50 UTC, PiotrDziedzic-dev approved these changes

2021-02-08 08:51 UTC, closed without merging