Detail repaired
piotr-grosicki/project-jdp-2101-01 pull request #18
Opened 2021-02-05 17:32 UTC by PiotrDziedzic-dev

2021-02-05 17:44 UTC, piotr-grosicki requested changes

2021-02-05 17:44 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public UserDto createUser(@RequestBody String userName, String userSurname, String userEMail) {
parametrem tej metody powinno byc dto z request body

2021-02-05 17:44 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public UserDto banUser(@RequestBody Long userId) {
bylo dobrze, skad pomysl na zmiane?

2021-02-05 17:44 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public Integer getKey(@RequestBody Long userId) {
bylo dobrze, skad pomysl na zmiane?

2021-02-06 23:10 UTC, PiotrDziedzic-dev commented
Główną poprawką w tym kontrolerze (odnosząc się do aktualnego maina) miało być poprawienie metody createUser() z GET na POST oraz dodanie tam w request body obiektu UserDto

2021-02-07 00:17 UTC, defiofi approved these changes

2021-02-08 10:02 UTC, KChwistek-prog approved these changes
Projekt buduje, postman coś tam zwraca. Ok

2021-02-08 18:51 UTC, piotr-grosicki approved these changes

2021-02-08 18:51 UTC, merged