Jdp210101 24
piotr-grosicki/project-jdp-2101-01 pull request #20
Opened 2021-02-05 18:57 UTC by KChwistek-prog

2021-02-05 19:40 UTC, defiofi commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    public Order showOrder(@PathVariable("orderId") Long orderId) throws  OrderNotFoundException {
Co robi @PathVariable(orderID), albo inaczej czym to się różni od @Requestparam?

2021-02-05 19:53 UTC, defiofi requested changes

2021-02-05 19:53 UTC, defiofi commented on src/main/java/com/kodilla/ecommercee/service/Database.java
> +    public Order saveOrder(final Order order){
saveOrder i addOrder - różnie się nazywają , ale robią dokładnie to samo. W takim razie czy nie mogło by zostać tylko saveOrder?

2021-02-05 20:23 UTC, KChwistek-prog commented on src/main/java/com/kodilla/ecommercee/service/Database.java
> +    public Order saveOrder(final Order order){
słusznie, robiac implementacje nie popatrzylem czy juz takiej nie ma, usuwam

2021-02-05 20:33 UTC, KChwistek-prog commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    public Order showOrder(@PathVariable("orderId") Long orderId) throws  OrderNotFoundException {
Generalnie mogło by być to i to. Różni je url jaki jest do przekazania parametru. url z RequestParam by wygladał chyba w ten deseń /showOrder?id=1. A że jest jeden parametr do przekazania to wzialem ten co wygląda czytelniej Ale szczerze to nie wiem jaka jest głębsza róznica między nimi. Moze przy bardziej skomplikowanych projektach ma to większe znaczenie.

2021-02-05 20:52 UTC, defiofi approved these changes

2021-02-06 21:05 UTC, piotr-grosicki requested changes
projekt sie nie buduje, nie bedzie mozna zmergowac :)

2021-02-08 01:56 UTC, PiotrDziedzic-dev approved these changes

2021-02-08 08:54 UTC, piotr-grosicki commented
projekt sie nadal nie buduje:

```/home/circleci/repo/src/main/java/com/kodilla/ecommercee/CartController.java:35: error: constructor OrderDto in class OrderDto cannot be applied to given types;
        return new OrderDto(1L,"New order");
               ^
  required: Long,String,String,Double,Timestamp,Timestamp,boolean```

2021-02-08 09:52 UTC, piotr-grosicki approved these changes

2021-02-08 09:52 UTC, merged