Entity Cart Done
piotr-grosicki/project-jdp-2101-01 pull request #22
Opened 2021-02-06 23:00 UTC by PiotrDziedzic-dev

2021-02-06 23:21 UTC, mateuszwojciak approved these changes
Kod się kompiluje, nie widzę błędów. Według mnie można poprawić oczyszczenie kodu o odstępy, aby utrzymać w całej klasie podobne odstępny pomiędzy metodami (liczba pustych linii między metodami).

2021-02-07 00:15 UTC, defiofi requested changes

2021-02-07 00:15 UTC, defiofi commented on src/main/java/com/kodilla/ecommercee/domain/User.java
>      @Column(name = "ID")
Proponuje dodać w tym miejscu:
@NotNull

2021-02-07 17:06 UTC, eimspl commented on src/main/java/com/kodilla/ecommercee/domain/User.java
>      @Column(name = "ID")
A to nie jest przypadkiem tak, że @Id z automatu wymusza @NotNull?

2021-02-07 17:23 UTC, eimspl approved these changes
Nie jestem na 100% tego NonNull czy musi być, ale to w niczym nie przeszkadza :)

2021-02-07 20:35 UTC, KChwistek-prog requested changes
Generalnie działa i wydaje się, że wszystko ok ale mam pytanie raczej o przejrzystość kodu: 
-skoro i tak jest lombok użyty nie lepiej dać @Getter i @Setter a adnotacje @Column ustawić na polach? Znacznie by to poprawiło czytelność i skróciło cały kod :)

2021-02-07 22:35 UTC, Piotr1992 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +            inverseJoinColumns = {@JoinColumn(name = "")} //tutaj czekam na encję product
inverseJoinColumns = {@JoinColumn(name = "PRODUCT_ID",referencedColumnName = "PRODUCT_ID")}

2021-02-08 00:29 UTC, PiotrDziedzic-dev commented
Zastosowałem się do waszych uwag, oprócz dodawania notNula ponieważ jest to encja USER więc nie chciałem mieszać zadań. Kod został skrócony i jest bardziej przejrzysty

2021-02-08 02:05 UTC, PiotrDziedzic-dev commented
PS Dodałem jednak NotNull do klasy User

2021-02-08 08:52 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/User.java
>      @Column(name = "ID")
tak dokladnie jest :)

2021-02-08 08:52 UTC, merged