JDP210101-34 zakomentowanie elementu orderDTO
piotr-grosicki/project-jdp-2101-01 pull request #24
Opened 2021-02-07 17:16 UTC by KChwistek-prog

2021-02-07 17:25 UTC, eimspl approved these changes
Ok, może jechać.

2021-02-07 18:01 UTC, defiofi requested changes

2021-02-07 18:01 UTC, defiofi commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +//    @RequestMapping(method = RequestMethod.GET, value = "createOrder")
Dlaczego metoda tworzenia koszyka to GET a nie POST ?

2021-02-07 18:17 UTC, KChwistek-prog commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +//    @RequestMapping(method = RequestMethod.GET, value = "createOrder")
nie wiem, nie moja klasa i nie moja metoda, ona ma wygladac inaczej i jest do napisania  od nowa ale dalem ja do komentowania bo calkowicie blokuje pelna implementacje order

2021-02-07 21:35 UTC, piotr-grosicki requested changes

2021-02-07 21:35 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +//    @RequestMapping(method = RequestMethod.GET, value = "createOrder")
Chwila, nie ma czegos takiego jak „nie moja klasa”, „nie moja metoda”. Caly kod jest Wasz wspolny i razem dzialacie w celu ukonczenia projektu. 

Komentowanie kodu, bez naprawienia jest nieakceptowalne. Jezeli cos jest nie tak i nie mozesz zakonczyc swojego zadania to Ty powinienes poprawic bledny kod lub przerobic go tak zeby wspolpracowal z tym co chcesz zrobic.

2021-02-07 22:01 UTC, KChwistek-prog commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +//    @RequestMapping(method = RequestMethod.GET, value = "createOrder")
Ok,  to wprowadze zmiany tutaj zakomentuje a w tasku z implementacja odkomentuje

2021-02-07 22:30 UTC, Piotr1992 commented on src/main/java/com/kodilla/ecommercee/CartController.java
>          return new ProductDto(3L,"Deleted product","Deleted description",100.100,10L);
Po ustaleniu encji tabel schematu bazy danych naszego projektu do klasy Product wstawiłem jeszcze jedno pole "UNIT".

2021-02-07 22:53 UTC, Piotr1992 requested changes

2021-02-07 22:53 UTC, Piotr1992 commented on src/main/java/com/kodilla/ecommercee/CartController.java
>          return new ProductDto(3L,"Deleted product","Deleted description",100.100,10L);
Należy dodać jeszcze jeden parametr "UNIT" do utworzenia instancji "ProductDto".

2021-02-08 08:17 UTC, KChwistek-prog commented on src/main/java/com/kodilla/ecommercee/CartController.java
>          return new ProductDto(3L,"Deleted product","Deleted description",100.100,10L);
W mainie nie ma zadnego pola unit.

2021-02-08 08:54 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +//    @RequestMapping(method = RequestMethod.GET, value = "createOrder")
w takim razie jaki sens jest tego taska? nie lepiej od razu zrobic poprawnie w tasku z implementacja?

2021-02-08 08:57 UTC, closed without merging