Jdp 210101 40
piotr-grosicki/project-jdp-2101-01 pull request #42
Opened 2021-02-11 21:07 UTC by eimspl

Połączeniue User z Cart (one to many)

2021-02-11 21:22 UTC, KChwistek-prog requested changes

2021-02-11 21:22 UTC, KChwistek-prog commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private List<Cart> carts = new ArrayList<>();
wydaje mi się, że tu powinno  bez tego new array bo inaczej przy kazdym odwolaniu będzie tworzyć pusta liste :)

2021-02-11 21:58 UTC, defiofi commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private List<Cart> carts = new ArrayList<>();
Tak powinno być tylko : private List<Cart> carts;

2021-02-11 21:59 UTC, defiofi commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private List<Cart> carts = new ArrayList<>();
znaczy się : private List<cart> carts;       :)

2021-02-11 22:02 UTC, mateuszwojciak commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private List<Cart> carts = new ArrayList<>();
Popieram komentarz wyżej. Ja bym przerzucił stworzenie pustej listy na samą górę klasy (w takiej formie w jakiej jest), a tutaj stworzył dodatkową metodę, która będzie zwracała Listę 'carts'.

2021-02-11 22:35 UTC, eimspl commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private List<Cart> carts = new ArrayList<>();
@KChwistek-prog Okey... czyli mam rozumieć private List<Cart> carts; ? Gettery i settery zrobią swoje. @mateuszwojciak  a wtedy po co zostawiać i wrzucać na górę?

2021-02-12 19:21 UTC, KChwistek-prog approved these changes

2021-02-12 19:24 UTC, PiotrDziedzic-dev approved these changes

2021-02-12 19:26 UTC, merged