ProductController - rzeczywista implementacja metod
piotr-grosicki/project-jdp-2101-01 pull request #44
Opened 2021-02-14 02:52 UTC by Piotr1992

Task JDP210101-21 "ProductController - rzeczywista implementacja metod"

2021-02-14 19:34 UTC, KChwistek-prog requested changes
Generalnie się uruchamia, postman też coś zwraca poprawnie ale nie ma wszyskich implementacji i nie można dokładnie przetestować ale na razie bym dał approve tylko, że zastanawia mnie jedna rzecz. Zmieniłeś nazwę klasy exception na ogólną która była zrobiona pod kątem obsługi błędów klasy Order stad nazwa. :) Wydaje mi się, że implementacje powinny mieć swoją własną obsługę błędów.

2021-02-14 20:05 UTC, Piotr1992 commented
> Generalnie się uruchamia, postman też coś zwraca poprawnie ale nie ma wszyskich implementacji i nie można dokładnie przetestować ale na razie bym dał approve tylko, że zastanawia mnie jedna rzecz. Zmieniłeś nazwę klasy exception na ogólną która była zrobiona pod kątem obsługi błędów klasy Order stad nazwa. :) Wydaje mi się, że implementacje powinny mieć swoją własną obsługę błędów.

2021-02-14 20:13 UTC, Piotr1992 commented
> Generalnie się uruchamia, postman też coś zwraca poprawnie ale nie ma wszyskich implementacji i nie można dokładnie przetestować ale na razie bym dał approve tylko, że zastanawia mnie jedna rzecz. Zmieniłeś nazwę klasy exception na ogólną która była zrobiona pod kątem obsługi błędów klasy Order stad nazwa. :) Wydaje mi się, że implementacje powinny mieć swoją własną obsługę błędów.

Czy mógłbyś podać dla jakich konkretnie implementacji postman nie zwraca poprawnych wyników.

2021-02-14 21:04 UTC, KChwistek-prog commented
> > Generalnie się uruchamia, postman też coś zwraca poprawnie ale nie ma wszyskich implementacji i nie można dokładnie przetestować ale na razie bym dał approve tylko, że zastanawia mnie jedna rzecz. Zmieniłeś nazwę klasy exception na ogólną która była zrobiona pod kątem obsługi błędów klasy Order stad nazwa. :) Wydaje mi się, że implementacje powinny mieć swoją własną obsługę błędów.
> 
> Czy mógłbyś podać dla jakich konkretnie implementacji postman nie zwraca poprawnych wyników.

Np. dodawanie produktu zapisuje w bazie danych same nulle.

2021-02-14 21:09 UTC, KChwistek-prog requested changes

2021-02-14 21:09 UTC, KChwistek-prog commented on src/main/java/com/kodilla/ecommercee/service/ProductDbService.java
> +        repository.save(new Product());
Pewnie to robi problem z nullowymi wartosciami w bazie

2021-02-14 21:40 UTC, defiofi requested changes

2021-02-14 21:40 UTC, defiofi commented on src/main/java/com/kodilla/ecommercee/CartController.java
createNewCart - to nie powinno korzystać z metody POST ? Być może nie ty to pisałeś...

2021-02-14 21:40 UTC, defiofi commented on src/main/java/com/kodilla/ecommercee/controller/NotFoundException.java
> +}
Co daje nam ta nowa klasa NotFoundException? Bo na razie to chyba to samo co by korzystać z Exception...

2021-02-14 21:40 UTC, defiofi commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +            productDto.getCarts()
productDto.getCarts() - my chyba nie chcemy informować przy każdym zapytaniu o produkt w jakich wózkach znajduje się ten produkt.

2021-02-14 21:40 UTC, defiofi commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +}
Przyznam się , że nie wiem po co są tu nadpisane metody: findAll() , save(Product product) , deleteById(Long id).
Chyba działało by i bez tego...

2021-02-14 22:09 UTC, defiofi commented on src/main/java/com/kodilla/ecommercee/service/ProductDbService.java
> +        repository.save(new Product());
https://snipboard.io/ZeJgCd.jpg
https://snipboard.io/XMOw25.jpg

2021-02-16 07:34 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/NotFoundException.java
> +}
uzywanie takich klas jest bardzo dobrym zwyczajem, dzieki temu nie musimy zastanawiac sie dlaczego taki exception polecial lecz sama nazwa juz jest pewnego rodzaju wskazowka

2021-02-16 07:38 UTC, piotr-grosicki requested changes

2021-02-16 07:38 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +    private Group groupId;
tak nie moze byc, w Dto nie trzymamy zaleznosci do encji a do innych dto

2021-02-16 07:38 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +    private List<Cart> carts;
tak nie moze byc, w Dto nie trzymamy zaleznosci do encji a do innych dto

2021-02-16 07:39 UTC, piotr-grosicki commented
konflikt w `CartController`

2021-02-17 00:57 UTC, closed without merging