Jdp210101 19
piotr-grosicki/project-jdp-2101-01 pull request #45
Opened 2021-02-14 19:38 UTC by defiofi

Wstępne testy encji Carts.

2021-02-15 19:38 UTC, PiotrDziedzic-dev commented on src/test/java/com/kodilla/ecommercee/TestDAO/CartTestSuite.java
> +        Optional<Cart> readCart = cartRepository.findById(1000L);
Wydaje mi się, że tutaj trzeba nadpisać metodę findById w CartRepository aby jej zwracany typ również był Optional<Cart>
Osobiście nie wsadzałbym tego id na "sztywno" do metody findById. Chyba lepiej zrobić 
long id - cart.getId(); a potem findyById(id); aczkolwiek wydaje mi się że to jest tylko kosmetyczna zmiana także jeśli wolisz żeby zostało tak jak jest teraz to jak najbardziej będzie OK

2021-02-15 19:38 UTC, PiotrDziedzic-dev commented on src/test/java/com/kodilla/ecommercee/TestDAO/CartTestSuite.java
> +        Optional<Cart> readCart = cartRepository.findById(2000L);
Tutaj tak samo j.w.

2021-02-15 19:38 UTC, PiotrDziedzic-dev commented on src/test/java/com/kodilla/ecommercee/TestDAO/CartTestSuite.java
> +        Optional<Cart> readCart1 = cartRepository.findById(3000L);
Tak samo j.w.

2021-02-15 19:38 UTC, PiotrDziedzic-dev commented on src/test/java/com/kodilla/ecommercee/TestDAO/CartTestSuite.java
> +        Optional<Cart> readCart2 = cartRepository.findById(3000L);
Tak samo j.w.

2021-02-15 19:38 UTC, PiotrDziedzic-dev commented on src/test/java/com/kodilla/ecommercee/TestDAO/CartTestSuite.java
> +        Optional<Cart> readCart1 = cartRepository.findById(4000L);
Tak samo j.w.

2021-02-15 19:39 UTC, PiotrDziedzic-dev commented on src/test/java/com/kodilla/ecommercee/TestDAO/CartTestSuite.java
> +import java.sql.Timestamp;
Wszędzie używasz Timestamp a w Cart jest Date

2021-02-15 19:46 UTC, PiotrDziedzic-dev requested changes

2021-02-15 19:46 UTC, PiotrDziedzic-dev commented on src/test/java/com/kodilla/ecommercee/TestDAO/CartTestSuite.java
> +        Cart cart = new Cart(1000L, new Timestamp(12345678900L), new Timestamp(12345900000L) ,false );
Tutaj tworzysz cart ale w konstruktorze zapomniałeś chyba o liście produktów którą cart ma.
(Ten sam błąd jest za każdym razem jak tworzysz Cart)

2021-02-15 20:39 UTC, defiofi commented on src/test/java/com/kodilla/ecommercee/TestDAO/CartTestSuite.java
> +        Optional<Cart> readCart = cartRepository.findById(1000L);
ok , tak zrobię.

2021-02-15 20:42 UTC, defiofi commented on src/test/java/com/kodilla/ecommercee/TestDAO/CartTestSuite.java
> +import java.sql.Timestamp;
Tak to prawda. Wcześniej miałem Date i było dokładnie tak samo. Wiec wydaje mi się , że to nie ma wpływu na rezultat końcowy testów.

2021-02-15 20:43 UTC, defiofi commented on src/test/java/com/kodilla/ecommercee/TestDAO/CartTestSuite.java
> +        Cart cart = new Cart(1000L, new Timestamp(12345678900L), new Timestamp(12345900000L) ,false );
ponieważ , połączenie z product jest jeszcze w komentarzach. Gdy pisałem ten branch nie było jeszcze połączenia encji i nie było repozytorium. chyba nadal go nie ma.

2021-02-16 07:42 UTC, piotr-grosicki requested changes

2021-02-16 07:42 UTC, piotr-grosicki commented on git status
> +  JDP210101-15[m
co to za plik i czemu zostal dodany do gita?

2021-02-16 07:42 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/TestDAO/CartTestSuite.java
> +public class CartTestSuite {
testy nie przechodza

```com.kodilla.ecommercee.TestDAO.CartTestSuite > TestCartDaoModification FAILED
    org.springframework.dao.InvalidDataAccessApiUsageException at CartTestSuite.java:94
        Caused by: java.lang.IllegalStateException at CartTestSuite.java:94
            Caused by: org.hibernate.TransientPropertyValueException at CartTestSuite.java:94```
            
prawdopodobnie brakuje `Transactional` nad klasa testowa lub odpowiednich kaskad w encjach

2021-02-16 07:42 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/TestDAO/CartTestSuite.java
> +    public void TestCartDaoDelete() {
brakuje sprawdzenia co sie dzieje z userem i produktami po usunieciu koszyka

2021-02-16 19:38 UTC, defiofi commented on src/test/java/com/kodilla/ecommercee/TestDAO/CartTestSuite.java
> +public class CartTestSuite {
rzeczywiście nie dałem tej adnotacji. Dodam.

2021-02-18 09:45 UTC, piotr-grosicki requested changes
projekt sie nie buduje

2021-02-19 12:56 UTC, closed without merging