Encja product testy
piotr-grosicki/project-jdp-2101-01 pull request #46
Opened 2021-02-14 20:35 UTC by Piotr1992

Zadanie wykonywane na bieżąco.

2021-02-16 07:44 UTC, piotr-grosicki requested changes
testy nie przechodza

```com.kodilla.ecommercee.TestDAO.ProductTestSuite > TestProductDtoSave FAILED
    org.springframework.dao.InvalidDataAccessApiUsageException at ProductTestSuite.java:31
        Caused by: java.lang.IllegalStateException at ProductTestSuite.java:31
            Caused by: org.hibernate.TransientPropertyValueException at ProductTestSuite.java:31```
            
            brakuje prawdopodobnie `Transactional` nad klasa testowa lub odpowiednich kaskad w encjach

2021-02-16 07:44 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/TestDAO/ProductTestSuite.java
> +/*        Optional<Product> read = productRepository.findById(1L);
w kodzie NIGDY nie zostawiamy zadnego zakomentowanego kodu, wszystko co jest niepotrzebne usuwamy. jezeli chcemy do niego kiedys wrocic to mamy git log

2021-02-18 01:03 UTC, Piotr1992 commented on src/test/java/com/kodilla/ecommercee/TestDAO/ProductTestSuite.java
> +/*        Optional<Product> read = productRepository.findById(1L);
Ten branch do tak naprawdę tylko do celów testowych, żeby innymi uczestnicy mogli sprawdzić kod.

2021-02-20 19:33 UTC, closed without merging

2021-02-20 19:34 UTC, Piotr1992 commented
Ten testowy branch już nie jest aktualny.