Entity has been tested
piotr-grosicki/project-jdp-2101-01 pull request #47
Opened 2021-02-15 18:58 UTC by PiotrDziedzic-dev

2021-02-15 21:05 UTC, KChwistek-prog requested changes
Generalnie wporzo ale mieszasz asercje. Powinieneś używać junit a nie jupiter więc te zmiany w gradle nie sa koniecznie a sprawdzanie powinno być przez assertTrue(readGroup.isPresent()); 
 zamiast 
 Assertions.assertTrue(readGroup.isPresent()); które jest z jupitera.

2021-02-15 21:34 UTC, defiofi requested changes

2021-02-15 21:34 UTC, defiofi commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +
W repository tworzysz deleteById(). Interface CrudRepository ma już w sobie deleteById() , więc chyba niepotrzebnie jest tworzony. 
Optional<Group> findById(long Long); - OK , ale może warto go nadpisać? @Override

2021-02-15 21:34 UTC, defiofi commented on src/test/java/com/kodilla/ecommercee/group/dao/GroupRepositoryTestSuite.java
> +        group.setDescription("Second Description");
czy tutaj nie warto było by sprawdzić czy można zmodyfikować coś więcej niż tylko description ?
Po co zmieniać description przed zapisaniem do bazy danych? Wydaje mi się , że trzeba sprawdzić czy zmodyfikuje po zapisaniu do bazy danych.

2021-02-15 21:34 UTC, defiofi commented on src/test/java/com/kodilla/ecommercee/group/dao/GroupRepositoryTestSuite.java
> +        groupRepository.save(group);
Tak się zastanawiam , a może warto sprawdzić czy jest rekord zapisany w bazie danych zanim się go usunie?

2021-02-16 07:49 UTC, piotr-grosicki requested changes
testy nie przechodza

```com.kodilla.ecommercee.group.dao.GroupRepositoryTestSuite > GroupDaoUpdate FAILED
    org.springframework.dao.IncorrectResultSizeDataAccessException at GroupRepositoryTestSuite.java:78
        Caused by: javax.persistence.NonUniqueResultException at GroupRepositoryTestSuite.java:78```
jest to spowodowane tym, ze dwa (lub wiecej) testow dodaje grupe o tej samej nazwie. Cos zapewne nie dziala tez usuwanie encji po tescie (moze brakuje `Transactional` nad klasa testowa?

2021-02-16 07:49 UTC, piotr-grosicki commented on build.gradle
> +    testCompile group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.7.0'
czemu zostal dodany jupiter?

2021-02-16 07:49 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/group/dao/GroupRepositoryTestSuite.java
> +    public void GroupDaoDelete() {
brakuje sprawdzenia czy produkty zostaja w bazie danych po usunieciu grupy

2021-02-16 07:49 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/group/dao/GroupRepositoryTestSuite.java
> +        groupRepository.save(group);
troche nadgorliwosc, przeciez mamy test sprawdzajacy czy zapis dziala

2021-02-17 00:08 UTC, PiotrDziedzic-dev commented on build.gradle
> +    testCompile group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.7.0'
Racja mój błąd, już to naprawiłem

2021-02-17 00:10 UTC, PiotrDziedzic-dev commented
> Generalnie wporzo ale mieszasz asercje. Powinieneś używać junit a nie jupiter więc te zmiany w gradle nie sa koniecznie a sprawdzanie powinno być przez assertTrue(readGroup.isPresent());
> zamiast
> Assertions.assertTrue(readGroup.isPresent()); które jest z jupitera.

Racja, już poprawiłem. Dzięki

2021-02-17 00:12 UTC, PiotrDziedzic-dev commented
> testy nie przechodza
> 
> ```
>     org.springframework.dao.IncorrectResultSizeDataAccessException at GroupRepositoryTestSuite.java:78
>         Caused by: javax.persistence.NonUniqueResultException at GroupRepositoryTestSuite.java:78```
> jest to spowodowane tym, ze dwa (lub wiecej) testow dodaje grupe o tej samej nazwie. Cos zapewne nie dziala tez usuwanie encji po tescie (moze brakuje `Transactional` nad klasa testowa?
> ```

Dodałem adnotację Transactional. Testy ogólnie u mnie się wykonują i przechodzą poprawnie ale widzę że CircleCi nie przechodzi

2021-02-17 23:27 UTC, closed without merging