mysql connector -> build gradle, wstepna implementacja endpointow
piotr-grosicki/project-jdp-2101-01 pull request #5
Opened 2021-01-29 10:09 UTC by KChwistek-prog

2021-01-29 14:23 UTC, piotr-grosicki requested changes

2021-01-29 14:23 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public void addNewOrder(OrderDto orderDto){
brakuje adnotacji parametru

2021-01-29 14:23 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public OrderDto showOrder(Long id){
brakuje adnotacji parametru

2021-01-29 14:23 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public OrderDto updateOrder(OrderDto orderDto){
brakuje adnotacji parametru

2021-01-29 14:23 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public void removeOrder(Long orderId){
brakuje adnotacji parametru

2021-01-29 18:32 UTC, piotr-grosicki requested changes
konflikt w pliku `build.gradle`

2021-01-29 22:03 UTC, piotr-grosicki requested changes

2021-01-29 22:03 UTC, piotr-grosicki commented on build.gradle
> -    runtimeOnly'mysql:mysql-connector-java'
to nie powinno byc tutaj usuwane ;)

2021-01-29 22:31 UTC, KChwistek-prog commented on build.gradle
> -    runtimeOnly'mysql:mysql-connector-java'
Czy w takim wypadku usuniecie tutaj pliku z commita będzie zgodne ze sztuką?

2021-01-30 10:06 UTC, piotr-grosicki requested changes

2021-01-30 10:06 UTC, piotr-grosicki commented on build.gradle
> -    runtimeOnly'mysql:mysql-connector-java'
Teraz Twoja branch usuwa caly ten plik. Najprosciej wejsc na maina, skopiowac jego zawartosc, wkleic u siebie na branchy i zcommitowac

2021-01-30 10:47 UTC, piotr-grosicki approved these changes

2021-01-30 10:47 UTC, merged