Stworzenie testów CRUD dla Encji User
piotr-grosicki/project-jdp-2101-01 pull request #52
Opened 2021-02-17 22:14 UTC by mateuszwojciak

2021-02-18 09:49 UTC, piotr-grosicki requested changes
konflikty

2021-02-19 01:46 UTC, PiotrDziedzic-dev requested changes
Są konflikty w 1 pliku, zrebasuj do maina i wystarczy usunąć kilka linijek które powodują konfilkt

2021-02-19 21:45 UTC, defiofi requested changes

2021-02-19 21:45 UTC, defiofi commented on src/test/java/com/kodilla/ecommercee/user/dao/UserRepositoryTestSuite.java
> +
To działa , tylko się zastanawiam dlaczego w tym miejscu szukasz po username , a przecież masz ID i możesz użyć findById().

2021-02-19 21:45 UTC, defiofi commented on src/test/java/com/kodilla/ecommercee/user/dao/UserRepositoryTestSuite.java
> +        userRepository.deleteById(userOneId);
Mam takie wrażenie , że tworzysz userOne tylko po to by go na końcu skasować, ale do testu jest ci to w ogóle nie potrzebne...

2021-02-20 13:18 UTC, mateuszwojciak commented on src/test/java/com/kodilla/ecommercee/user/dao/UserRepositoryTestSuite.java
> +
Początkowo tak chciałem zrobić, ale wtedy User muszę zrobić w Optional i nie mogę użyć AssertEquals.

2021-02-20 21:01 UTC, defiofi commented on src/test/java/com/kodilla/ecommercee/user/dao/UserRepositoryTestSuite.java
> +
ależ możesz... 
Optional<Cart> readCart = cartRepository.findById(id);
        assertEquals( new Date(12345678900L), readCart.map(Cart::getDateOfReservation).orElse(new Date(1L)));
to przykład z moich testów.

2021-02-21 00:31 UTC, PiotrDziedzic-dev commented
Chyba wszystko wygląda dobrze

2021-02-21 00:31 UTC, PiotrDziedzic-dev approved these changes

2021-02-21 23:06 UTC, defiofi approved these changes

2021-02-22 02:15 UTC, Piotr1992 approved these changes

2021-02-22 08:31 UTC, piotr-grosicki approved these changes

2021-02-22 08:31 UTC, merged