JDP210101-22 - GroupControler rzeczywista implementacja metod
piotr-grosicki/project-jdp-2101-01 pull request #53
Opened 2021-02-17 22:50 UTC by defiofi

Rzeczywista implementacja metod. 
Pozwoliłem sobie zrobić drobną modyfikację w Ordercontroller.

2021-02-18 19:07 UTC, KChwistek-prog requested changes

2021-02-18 21:28 UTC, defiofi commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +        return groupMapper.mapToGroupDto(searchedGroup.orElseThrow(RuntimeException::new));
Może to jest lepiej jak jest nowy wyjątek , ale ja bym chciał wiedzieć dlaczego to jest lepiej? 
koledzy zrobili OrderNotFoundException , ale jeżeli nie robi nic więcej niż exception to po co robić?

2021-02-19 08:20 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +        return groupMapper.mapToGroupDto(searchedGroup.orElseThrow(RuntimeException::new));
poniewaz nazwa wskazuje od razu co sie stalo. rzucanie czystych `RuntimeException` i `Exception` jest bardzo zla praktyka. Wyjatki staramy sie zawsze robic tak zeby sama ich nazwa tlumaczyla istote i domene problemu

2021-02-19 21:47 UTC, defiofi commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +        return groupMapper.mapToGroupDto(searchedGroup.orElseThrow(RuntimeException::new));
To ja w takim razie zrobię klasę błędu.

2021-02-21 00:43 UTC, PiotrDziedzic-dev commented
3 pliki powodują konflikty

2021-02-21 01:31 UTC, closed without merging

2021-02-21 01:31 UTC, defiofi commented
Zastąpiony przez JDP210101-22_REV03