Testy encji Group
piotr-grosicki/project-jdp-2101-01 pull request #54
Opened 2021-02-17 23:33 UTC by PiotrDziedzic-dev

2021-02-17 23:39 UTC, PiotrDziedzic-dev commented
Stara branch usunięta ze względu na ilość błędów które w niej występowały

2021-02-18 04:12 UTC, KChwistek-prog requested changes
circle nie przechodzi, wywala błąd: com.kodilla.ecommercee.group.dao.GroupRepositoryTestSuite > GroupDaoDelete FAILED
    java.lang.AssertionError at GroupRepositoryTestSuite.java:122

2021-02-19 18:54 UTC, piotr-grosicki approved these changes

2021-02-19 18:59 UTC, mateuszwojciak approved these changes

2021-02-19 19:01 UTC, merged