Jdp210101 23 - Rzeczywista implementacja kontrolera Cart
piotr-grosicki/project-jdp-2101-01 pull request #62
Opened 2021-02-20 19:13 UTC by eimspl

Rzućcie okiem

2021-02-20 19:21 UTC, KChwistek-prog requested changes

2021-02-20 19:21 UTC, KChwistek-prog commented on src/main/java/com/kodilla/ecommercee/controller/ProductNotFoundException.java
> +package com.kodilla.ecommercee.controller;public class ProductNotFoundException {
z enterem bylo by ładniej :)

2021-02-20 19:21 UTC, KChwistek-prog commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +
w encji chyba nie powinno byc metody addproduct

2021-02-20 20:57 UTC, defiofi requested changes

2021-02-20 20:57 UTC, defiofi commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "getNewCart")
Uważam , że kreacja powinna być przez POST

2021-02-20 21:08 UTC, eimspl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +
> w encji chyba nie powinno byc metody addproduct

A gdzie proponujesz? :)

2021-02-21 07:17 UTC, eimspl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "getNewCart")
W zasadzie masz racje :)

2021-02-21 08:57 UTC, KChwistek-prog approved these changes

2021-02-21 12:44 UTC, defiofi approved these changes

2021-02-21 13:11 UTC, merged