poprawa Task JDP210101-21
piotr-grosicki/project-jdp-2101-01 pull request #63
Opened 2021-02-20 19:39 UTC by Piotr1992

ProductController - rzeczywista implementacja metod

2021-02-20 19:41 UTC, KChwistek-prog commented
Musisz zrobic update maina w tym branchu bo jest nieaktualny :)

2021-02-20 20:48 UTC, defiofi requested changes

2021-02-20 20:48 UTC, defiofi commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                new GroupDto(1L, "name of group", "desc of group")
Wydaje mi się , że musisz użyć konstruktora bez ID. No bo po co nadawać cały czas ID = 1 ?

2021-02-20 20:48 UTC, defiofi commented on src/main/java/com/kodilla/ecommercee/service/ProductDbService.java
> +        repository.save(new Product(8L,"Product","Description",99.56, "szt.", new Group(4L, "Group", "Desc", new ArrayList<Product>()), new HashSet<Cart>()));
to samo może lepiej użyc konstruktorów bez ID ?

2021-02-20 23:52 UTC, Piotr1992 commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                new GroupDto(1L, "name of group", "desc of group")
Tutaj próbowałem bez Id wywołać konstruktor bez id i niestety się nie da.

2021-02-20 23:53 UTC, Piotr1992 commented on src/main/java/com/kodilla/ecommercee/service/ProductDbService.java
> +        repository.save(new Product(8L,"Product","Description",99.56, "szt.", new Group(4L, "Group", "Desc", new ArrayList<Product>()), new HashSet<Cart>()));
Tutaj dwa konstruktora bez ID poszły bez żadnego problemu.

2021-02-21 00:37 UTC, defiofi approved these changes

2021-02-21 00:40 UTC, PiotrDziedzic-dev commented
Dla mnie wygląda Ok

2021-02-21 00:40 UTC, PiotrDziedzic-dev approved these changes

2021-02-21 01:45 UTC, merged