JDP210101-11 wstępne przygotowanie tabel
piotr-grosicki/project-jdp-2101-01 pull request #7
Opened 2021-01-30 16:02 UTC by KChwistek-prog

2021-01-31 17:09 UTC, piotr-grosicki requested changes

2021-01-31 17:09 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
>  public class Order {
encja order powinna zawierac w sobie liste produktow i uzytkownika, ewentualnie koszyk (wszystko zalezy od tego jak zaplanujecie baze danych)

2021-02-01 16:07 UTC, piotr-grosicki requested changes

2021-02-01 16:07 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private Integer user_id;
encje w hibernate powinny zawierac klucze obce w postaci encji, nie ich id + brakuje adnotacji

2021-02-01 16:07 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private Integer cart_id;
encje w hibernate powinny zawierac klucze obce w postaci encji, nie ich id + brakuje adnotacji

2021-02-01 16:07 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    @Column(columnDefinition = "VARCHAR(20)")
Column zawiera parametr `length`

2021-02-01 16:07 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    @Column(columnDefinition = "VARCHAR(15)")
Column zawiera parametr `length`

2021-02-01 16:07 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private java.sql.Date paymentDate;
lepiej uzyc javowego `Timestamp` niz starego sql Date + brakuje adnotacji

2021-02-01 16:07 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private java.sql.Date realisationDate;
lepiej uzyc javowego `Timestamp` niz starego sql Date + brakuje adnotacji

2021-02-01 16:07 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private Double totalValue;
brakuje adnotacji

2021-02-01 16:07 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private boolean isPaid;
brakuje adnotacji

2021-02-01 18:17 UTC, KChwistek-prog commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private boolean isPaid;
Hibernate w encji ładnie tworzy tabelki nawet bez adnotacji Column (name = ""), idealnie nawet konwertuje camelCase na nazwy z podkreslnikami, dlatego stwierdzilem ze skoro bez column name "is_paid" i tak tabela nazywa się is_paid to może nie trzeba by jej dodawać. Ale jak rozumiem jest to błąd i juz poprawiam. :)

2021-02-01 19:21 UTC, KChwistek-prog commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private boolean isPaid;
czy wystarczy samo @Column bez nadawania nazwy?

2021-02-01 19:27 UTC, KChwistek-prog commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
>  public class Order {
tu tez mam pytanie, szukajac o polaczeniach tabel trafilem na 2 różne wersje, jedna to wlasnie 
@Entity(name = "")
 i druga zeby uzywac:
@Entity
@Table(name = "orders")
public class Order {}
jak jest poprawnie?

2021-02-01 20:34 UTC, KChwistek-prog commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private boolean isPaid;
Jeszcze jedno odnosnie tej encji, razem z nia powinienem poprawic orderDTO a razem z order DTO klase orderController bo sie wysypie na czerwono. moge to zrobic w tym commicie czy w tym zrobic tylko encje a dto i kontroler w nowym tasku?

2021-02-02 08:41 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private boolean isPaid;
dto mozna zostawic tak jak jest narazie

2021-02-02 08:41 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
>  public class Order {
table z name

2021-02-02 08:42 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private boolean isPaid;
co do adnotacji column, to lepiej jak sie dodaje do wszystkich pol, ktore maja byc polami encji (wieksza czytelnosc)

2021-02-02 08:42 UTC, piotr-grosicki approved these changes

2021-02-02 08:42 UTC, merged